server {
    listen 80;
    server_name daiswhat.com;

    
    location ^~ /actuator {
        # 뒤에 /actuator를 붙이지 말고 딱 포트까지만 적으세요.
    # 이렇게 하면 Nginx가 받은 /actuator/... 경로를 그대로 Spring에 넘깁니다.
    proxy_pass http://spring-api:8080; 
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 백엔드 API 요청은 Spring Boot 컨테이너로 토스 (Reverse Proxy)
    location ^~ /api {
        proxy_pass http://spring-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

        # Grafana 접속 (daiswhat.com/grafana)
    location /grafana/ {
        proxy_pass http://dais-grafana:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Prometheus 접속 (daiswhat.com/prometheus)
    location /prometheus/ {
        proxy_pass http://dais-prometheus:9090;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # ⭐ 이 설정이 핵심입니다! 
        # 경로를 못 찾으면 index.html로 보내서 Vue Router가 처리하게 합니다.
        try_files $uri $uri/ /index.html;
    }

    
    
}